### PR TITLE
v2.2a, prepare for Django4

### PR DESCRIPTION
**Pull request by legion-an**

### CODE REVIEW

**Review by creyD — APPROVED** [review]
@legion-an I believe that most of the adjustments were already in #27. I am currently running 2.0.0 on Django 4, and it works like a charm.

**Comment by legion-an** [comment]
> 

if you use 2.0.0 then it will work, yes, but with latest changes it won't, that's why I created this small fix

**Comment by creyD** [comment]
Very well, thank you!

**Comment by creyD** [comment]
@legion-an I don't think this is necessarily a new version. If you think so, then maybe we should stick to semantic versioning. Otherwise I will merge this today?

**Comment by legion-an** [comment]
yes, I guess we can merge

**Pull request merged**
